include ../Makefile_base

LAB_NUM=4

FILES=in40a.txt in40b.txt out40.txt
ARGS=$(FILES)

TEST_FILES=in41a.txt in41b.txt out41.txt
#_lab4
TEST_ARGS=in41a.txt in41b.txt out41.txt

_lab4: lab4.c
	gcc  -o _lab4 -lm lab4.c
	#-O3 -fomit-frame-pointer
