include ../Makefile_base

LAB_NUM=5

FILES=in50a.txt out50.txt
ARGS=$(FILES)

TEST_FILES=in51a.txt out51.txt
TEST_ARGS=$(TEST_FILES)

_lab5: lab5.c
	gcc -o _lab5 -lm lab4.c
	#-O3 -fomit-frame-pointer
